project_id = "ivtqvlzkrnvfoxscqouz"

[functions.migrate-openpos]
verify_jwt = false

[functions.sync-menu-inventory]
verify_jwt = false

[functions.import-staff]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false
